services:
  - type: web
    name: ai-therapist
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false # This means you'll set it manually in the Render dashboard
      - key: PORT
        value: 3000 